"""empty message

Revision ID: 70d87a271308
Revises: 1bc92443b749
Create Date: 2022-12-12 14:56:55.219224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70d87a271308'
down_revision = '1bc92443b749'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character', sa.Column('biografy', sa.String(length=200), nullable=True))
    op.add_column('character', sa.Column('url_img', sa.String(length=120), nullable=True))
    op.alter_column('character', 'gender',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=80),
               existing_nullable=True)
    op.drop_column('character', 'hair_color')
    op.add_column('planet', sa.Column('description', sa.String(length=200), nullable=True))
    op.add_column('planet', sa.Column('url_img', sa.String(length=120), nullable=True))
    op.drop_column('planet', 'clime')
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('planet', sa.Column('clime', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.drop_column('planet', 'url_img')
    op.drop_column('planet', 'description')
    op.add_column('character', sa.Column('hair_color', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.alter_column('character', 'gender',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
    op.drop_column('character', 'url_img')
    op.drop_column('character', 'biografy')
    # ### end Alembic commands ###
