"""empty message

Revision ID: cfef7fa678f4
Revises: 70d87a271308
Create Date: 2023-01-02 10:29:00.456898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfef7fa678f4'
down_revision = '70d87a271308'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('favorite_character', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('favorite_character', 'character_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('favorite_planet', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('favorite_planet', 'planet_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('favorite_planet', 'planet_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('favorite_planet', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('favorite_character', 'character_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('favorite_character', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
